Our in-tree gadu-gadu lib doesn't include the glib headers.  I don't know if that's something we want to do or not, so I changed these two g_ascii_strcasecmp() calls to strcasecmp() so that it compiles once again.
The error was:
lib/pubdir50.c: In function 'gg_pubdir50_handle_reply':
lib/pubdir50.c:350: error: implicit declaration of function 'g_ascii_strcasecmp'
lib/pubdir50.c:350: warning: nested extern declaration of 'g_ascii_strcasecmp'

--HG--
extra : convert_revision : 93a5063c46e94d1cc7ac11a05b7772048dc95753