[gaim-migrate @ 14241] sf patch #1343759, from Evan Schoenberg
Compilation error: A function depending on GAIM_PLUGINS-only
functions wasn't properly guarded with #ifdef GAIM_PLUGINS /
#endif

And some other changes to make things better when using static PRPLs

committer: Mark Doliner <markdoliner@pidgin.im>

--HG--
extra : convert_revision : 0e34ba6134d7f02b8878a89589a2de67f3346c12